sudo: false
languange: rust
rust:
  - nightly
cache:
  cargo: true
  wasm-pack: true
  yarn: true
  directories:
    - node_modules
    - target
jobs:
  include:
    before-install:
      - nvm install 12.4.0
    script:
      - yarn
      - yarn build
      - yarn deploy
